contact_booking/contact_booking/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('info_app.urls')),
    path('user/', include('user_app.urls')),
]

contact_booking/info_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = 'info_data'

urlpatterns = [
    path('', views.EmployeeList.as_view(), name='home_page'),

    path('create_record/', login_required(TemplateView.as_view(template_name='create_contact.html')), name='create_record'),
    
    path('employee_create/', views.EmployeeCreate.as_view(), name='employee_create'),

    path('employee/<int:pk>/update', views.EmployeeUpdate.as_view(), name='employee_update'),

    path('employee/<int:pk>/delete', views.EmployeeDelete.as_view(), name='employee_delete'),

    path('employee/<int:pk>/detail', views.EmployeeDetails.as_view(), name='employee_details'),

]

contact_booking/user_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, LoginView
from .views import ValidateUser

app_name = "user"

urlpatterns = [
    path('login/', TemplateView.as_view(template_name='login.html'), name='login'),
    path('validate_user/', ValidateUser.as_view(), name='validate_user'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

contact_booking/templates/contact_list.html
{% extends 'home_page.html' %}
{% load static %}

{% block title %}User List{% endblock title %}

{% block main_content %}
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h4 class="m-0">Employee Contact List</h4>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a class="btn btn-app bg-success" href="{% url 'info_data:create_record' %}"
                            style="border-radius: 15px;border:'';height: 55px;margin:'';min-width: 70px;">
                            <span class="badge bg-purple">891</span>
                            <i class="fas fa-address-book"></i>Add Users
                        </a>
                    </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Search Filter</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <!-- we are adding the accordion ID so Bootstrap's collapse plugin detects it -->
                        <div id="accordion">
                            <div class="card card-success">
                                <div class="card-header">
                                    <h4 class="card-title w-100">
                                        <a class="d-block w-100" data-toggle="collapse"
                                            href="#collapseThree">
                                            Search Options
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseThree" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        HELLO
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>S.no</th>
                                    <th colspan="3">Action</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>D.O.B</th>
                                    <th>Blood Group</th>
                                    <th>Gender</th>
                                    <th>City</th>
                                    <th>state</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in Employee_list_obj %}
                                <tr>
                                    <td>{{i.id}}</td>

                                    <td><a href="#" class="view-btn" data-id="{{i.id}}"><i class="fas fa-eye"></i></a></td>

                                    <!-- <td><a href="{% url 'info_data:employee_details' i.id %}"><i class="fas fa-eye"></i></a></td> data-toggle="modal" data-target="#view_modal" data-id="{{i.id}}" -->

                                    <td><a href="{% url 'info_data:employee_update' i.id %}"><i class="fas fa-edit"></i></a></td>

                                    <td><a href="#" class="delete-btn" data-toggle="modal" data-target="#del_modal" data-id="{{i.id}}"><i class="fas fa-trash-alt"></i></a></td>

                                    <td>{{i.first_name}}</td>
                                    <td>{{i.last_name}}</td>
                                    <td>{{i.email}}</td>
                                    <td>{{i.mobile_number}}</td>
                                    <td>{{i.date_of_birth}}</td>
                                    <td>{{i.blood_group}}</td>
                                    <td>{{i.gender}}</td>
                                    <td>{{i.city}}</td>
                                    <td>{{i.state}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->

{% endblock main_content %}

contact_booking/templates/delete_modal.html
<div class="modal fade" id="del_modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Delete Modal</h4>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete these Records?&hellip;</p>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a href="#" id="delete-link" class="btn btn-danger">Delete</a>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->

contact_booking/templates/home_page.html
{% extends 'base.html' %}
{% load static %}



{% block style %}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- IonIcons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

<link rel="stylesheet" href="{% static 'css/form-wizard.css' %}">
<style>
    
    * {
        box-sizing: border-box;
    }

    .form-wizard-wrapper {
        font-family: 'Lato', sans-serif;
        font-size: 16px;
    }

    .clearfix:after {
        display: block;

    }

    .form-column {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 50%;
        flex: 0 0 50%;
        max-width: 50%;
    }

    .full-wdth {
        width: 100%;
    }

    .form-column,
    .full-wdth {
        position: relative;
        min-height: 1px;
        padding-right: 15px;
        padding-left: 15px;
        margin-bottom: 10px;
    }

    .float-right {
        float: right;
    }

    .float-left {
        float: left;
    }

    label {
        display: inline-block;
        margin-bottom: .5rem;
    }

    .form-row {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-right: -15px;
        margin-left: -15px;
    }

    .form-wizard-wrapper {
        /*max-width: 767px;*/
        margin: 0 1%;
        overflow: hidden;
        position: relative;
        padding-top: 15px;
        z-index: 1;
    }

    .form-wizard-wrapper .form-wizardmove-button {
        position: absolute;
        width: 153.4px;
        left: 0;
        top: -4px;
        bottom: -4px;
        border-radius: 4px;
        background-color: #6f6fa7;
        -webkit-transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;
        -moz-transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;
        -ms-transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;
        -o-transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;
        transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;

    }

    .form-wizard-wrapper ul {
        background-color: #3bb6b6;
        z-index: 1;
        border-radius: 4px;
        display: flex;
        justify-content: center;
        position: relative;
        margin: 0;
        padding: 0;
    }

    .form-wizard-wrapper ul li {
        list-style-type: none;
        width: 100%;
        text-align: center;
        display: flex;
        justify-content: center;
    }

    .form-wizard-wrapper ul li a {
        display: block;
        padding: 10px;
        width: 100%;
        color: #ffffff;
        text-decoration: none;
    }

    .form-wizard-wrapper ul li a:focus {
        outline: 0;
    }

    .form-wizard-wrapper ul li a span {
        position: relative;
        z-index: 1;
    }

    .form-wizard-wrapper ul li.active a {
        background-color: #ffffff;
    }

    .form-wizard-wrapper .form-wizard-content {
        background-color: #ffffff;
        padding: 20px;
        color: #777777;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        transition: all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1) 0s;
        transform: translate3d(100%, 0px, 0px);
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
    }

    .form-wizard-wrapper .form-wizard-content.show {
        transform: translate3d(0px, 0px, 0px);
    }

    .form-wizard-wrapper .form-wizard-content h6 {
        font-size: 18px;
        font-weight: bold;
        margin: 0 0 10px;
    }

    .form-wizard-wrapper .form-wizard-content .form-wizard-next-btn,
    .form-wizard-wrapper .form-wizard-content .form-wizard-previous-btn {
        background-color: #3bb6b6;
        color: #ffffff;
        display: inline-block;
        padding: 6px 26px;
        border-radius: 4px;
        margin-top: 20px;
        text-decoration: none;
    }

    .form-wizard-wrapper .form-wizard-content .form-wizard-previous-btn {
        background-color: #f1f1f1;
        color: #000000;
    }

    .form-wizard-content-wrapper {
        height: 500px;
        position: relative;
        background-color: #fff;
    }

    .text-field {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }
    .form-wizard-link{
        pointer-events: none;
    }
</style>
<style>

    .content-area-edit_save {
        background: #fff;
        border: 1px solid #E2E2E2;
        padding: 50px;
        width: 600px;
        margin: 50px auto;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .row_edit_save {
        border-bottom: 1px solid #d8d8d8;
        padding: 10px 0;
        width: 100%;
    }

    .field {
        display: inline-block;
        position: relative;
        border-right: 1px solid #d8d8d8;
        margin-left: 20px;
        padding-right: 20px;
        transition: all 0.3s ease-in-out;
    }

    .field:last-of-type {
        border-right: none;
        padding-right: 0;
    }

    label {
        display: block;
        font-size: 12px;
        text-transform: uppercase;
        color: #9AA9AA;
        margin-top: 10px;
    }

    .edit-save {
        background: transparent;
        font-size: 16px;
        color: #444;
        border: none;
        border-bottom: 1px solid #d8d8d8;
        margin: 0 0 0 -2px;
        height: 40px;
        line-height: 40px;
        width: 100%;
        transition: all 0.3s ease-in-out;
        outline: none;
    }

    .edit-save[type="email"] {
        cursor: pointer;
        text-decoration: underline;
        color: #336699;
    }

    .button_edit_save {
        margin-bottom: 20px;
    }

    .button_edit_save a {
        display: inline-block;
        font-size: 14px;
        text-decoration: none;
        border-radius: 4px;
        padding: 0 15px;
        height: 40px;
        line-height: 40px;
        box-sizing: border-box;
        transition: all 0.3s ease-in-out;
    }

    .button_edit_save a.edit_edit_save {
        background-color: #FAFCFE;
        color: #3E4550;
        text-shadow: 1px 1px 0 #fff;
        border: 1px solid #DAE0E1;
    }

    .button_edit_save a.edit_edit_save:hover {
        background-color: #F2F5F7;
        border: 1px solid #D5DCDD;
    }

    .button_edit_save a.edit_edit_save:active {
        background-color: #E6ECF1;
        border: 1px solid #D5DADB;
    }

    .button_edit_save a.save_edit_save {
        display: none;
        background-color: #18A6F5;
        color: #fff;
        text-shadow: 1px 1px 0px rgba(0, 0, 0, 0.25);
        border: 1px solid #0F7AAC;
    }

    .button_edit_save a.save_edit_save:hover {
        background-color: #1A92D7;
        border: 1px solid #0E76A7;
    }

    .button_edit_save a.save_edit_save:active {
        background-color: #0D6288;
        border: 1px solid #11658D;
    }

    html.active .row_edit_save {
        border-bottom: 1px solid #fff;
    }

    html.active .row_edit_save .field {
        margin-left: 13px;
        padding-right: 13px;
        border-right: 1px solid #fff;
    }

    html.active .button_edit_save a.edit_edit_save {
        display: none;
    }

    html.active .button_edit_save a.save_edit_save {
        display: inline-block;
    }
</style>
{% endblock style %}

{% block content %}
    <div class="wrapper">
        <!-- Top Nav -->
        {% include 'top_navbar.html' %}
        <!-- /Top nav -->

        <!-- Side Nav -->
        {% include 'side_navbar.html' %}
        <!-- /Side Nav -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            {% include 'delete_modal.html' %}

            {% include 'view_modal.html' %}

            {% block main_content %}
            
            {% endblock main_content %}
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2023-2024 <a href="https://adminlte.io">KGISL</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0<br> 
                <b style="color: #1abc9c;">Powered By KGISL</b>
            </div>
        </footer>
    </div>
    <!-- ./wrapper -->


{% endblock content %}

contact_booking/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login Page{% endblock title %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock style %}

{% block content %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <h1 class="heading_login" data-heading="B">Contact Booking</h1>
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static 'images/book_2.jpg' %}" alt="IMG">
            </div>

            <form class="login100-form validate-form" action="{% url 'user:validate_user' %}" method="POST">
                {% csrf_token %}
                <span class="login100-form-title">
                    <img src="{% static 'images/kgisl-icon.png' %}" alt="" style="max-width:150px;max-height:150px;">
                </span>

                <div class="wrap-input100 validate-input" data-validate = "Valid username is required: ex@abc.xyz">
                    <input class="input100" type="text" name="username" placeholder="Username" autocomplete="off" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password" autocomplete="off" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <a class="txt2">
                        <p class="text-center text-inverse">© KGISL All Rights Reserved 2023 - 2024 </p>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>  
{% endblock content %}

contact_booking/templates/side_navbar.html
{% load static %}

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{% static 'images/kglogo.png' %}" alt="KGISL Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">KGISL</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'images/user_login.png' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block" style="text-transform: capitalize;">{{user.username}}</a>
            </div>
        </div>
        
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Menu</li>
                <li class="nav-item side_bar_bg">
                    <a href="{% url 'info_data:home_page' %}" class="nav-link">
                        <i class="nav-icon fas fa-users nav-icon"></i>
                        <p class="menu_name">
                            Contact List
                        </p>
                    </a>
                </li>
                <li class="nav-item side_bar_bg">
                    <a href="{% url 'info_data:create_record' %}" class="nav-link">
                        <i class="nav-icon fas fa-plus-circle nav-icon"></i>
                        <p class="menu_name">
                            Create Contact
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

contact_booking/templates/top_navbar.html
{% load static %}

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-cog dl_icon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header"  style="text-transform: uppercase;
                letter-spacing: 4px;"><i class="fas fa-user mr-2"></i> {{user.username}}</span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:logout' %}" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i> Logout
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="dark_mode" href="#" role="button">
                <i class="fa fa-moon dl_icon" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->